version: '3'

services:
  site:
    build: .
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - "4002:4000"
    command: jekyll serve --livereload --force_polling -H 0.0.0.0